const PERMISSION_LIST = {
    ADD_COMMENT: 'ADD_COMMENT',
    VIEW_BALANCE: 'VIEW_BALANCE',
    VIEW_SUBSCRIPTIONS: 'VIEW_SUBSCRIPTIONS',
    MAKE_IMPRESSION: 'MAKE_IMPRESSION',
    CRUD_SNIPPET: 'CRUD_SNIPPET',
    UPDATE_STATUS_SNIPPET: 'UPDATE_STATUS_SNIPPET',
    CRUD_TEMPLATE: 'CRUD_TEMPLATE',
    RECEIVE_MONEY: 'RECEIVE_MONEY'
}

export default PERMISSION_LIST
